services:
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'

  meilisearch:
    image: getmeili/meilisearch
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'

