name: PHP Composer

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --ignore-platform-reqs
    - name: Laravel Pint    
      run: php vendor/bin/pint --test
