name: PHPUnit

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: PHPUnit
      run: php vendor/bin/phpunit --stop-on-defect
