name: PHPUnit

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  pest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Pest
      run: php vendor/bin/pest --stop-on-defect
